# Reporting.ps1
function Generate-SecurityReport {
    param(
        [hashtable]$AuditResults,
        [string]$OutputPath = ".\reports\"
    )
    
    Write-Host "`n=== GENERATING SECURITY REPORT ===" -ForegroundColor Cyan
    
    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $computerName = $env:COMPUTERNAME
    
    # 1. Generate TXT report
    $txtReport = @"
===========================================
     WINDOWS SECURITY AUDIT REPORT
===========================================
Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
Computer: $computerName
Audit Tool Version: 1.0
===========================================

OVERALL SECURITY SCORE: $($AuditResults.OverallScore)/100

$(if ($AuditResults.OverallScore -ge 80) {
    "STATUS: GOOD - System is reasonably secure"
} elseif ($AuditResults.OverallScore -ge 60) {
    "STATUS: FAIR - Some improvements needed"
} else {
    "STATUS: POOR - Immediate action required"
})

DETAILED FINDINGS:
==================

"@
    
    # Add system information
    if ($AuditResults.SystemInfo) {
        $txtReport += "1. SYSTEM INFORMATION`n"
        $txtReport += "   OS: $($AuditResults.SystemInfo.OSName)`n"
        $txtReport += "   Version: $($AuditResults.SystemInfo.OSVersion)`n"
        $txtReport += "   Build: $($AuditResults.SystemInfo.BuildNumber)`n"
        $txtReport += "   Security Score: $($AuditResults.SystemInfo.SecurityScore)/100`n"
        
        if ($AuditResults.SystemInfo.Issues.Count -gt 0) {
            $txtReport += "   Issues:`n"
            foreach ($issue in $AuditResults.SystemInfo.Issues) {
                $txtReport += "     • $issue`n"
            }
        }
        $txtReport += "`n"
    }
    
    # Add account information
    if ($AuditResults.AccountInfo) {
        $txtReport += "2. ACCOUNT SECURITY`n"
        $txtReport += "   Security Score: $($AuditResults.AccountInfo.Score)/100`n"
        
        if ($AuditResults.AccountInfo.Issues.Count -gt 0) {
            $txtReport += "   Issues:`n"
            foreach ($issue in $AuditResults.AccountInfo.Issues) {
                $txtReport += "     • $issue`n"
            }
        }
        
        if ($AuditResults.AccountInfo.Recommendations.Count -gt 0) {
            $txtReport += "   Recommendations:`n"
            foreach ($rec in $AuditResults.AccountInfo.Recommendations) {
                $txtReport += "     • $rec`n"
            }
        }
        $txtReport += "`n"
    }
    
    # Add network information
    if ($AuditResults.NetworkInfo) {
        $txtReport += "3. NETWORK SECURITY`n"
        $txtReport += "   Security Score: $($AuditResults.NetworkInfo.Score)/100`n"
        
        if ($AuditResults.NetworkInfo.Issues.Count -gt 0) {
            $txtReport += "   Issues:`n"
            foreach ($issue in $AuditResults.NetworkInfo.Issues) {
                $txtReport += "     • $issue`n"
            }
        }
        $txtReport += "`n"
    }
    
    # Add Windows Defender information
    if ($AuditResults.DefenderInfo) {
        $txtReport += "4. WINDOWS DEFENDER`n"
        $txtReport += "   Security Score: $($AuditResults.DefenderInfo.Score)/100`n"
        
        if ($AuditResults.DefenderInfo.Issues.Count -gt 0) {
            $txtReport += "   Issues:`n"
            foreach ($issue in $AuditResults.DefenderInfo.Issues) {
                $txtReport += "     • $issue`n"
            }
        }
        
        if ($AuditResults.DefenderInfo.Recommendations.Count -gt 0) {
            $txtReport += "   Recommendations:`n"
            foreach ($rec in $AuditResults.DefenderInfo.Recommendations) {
                $txtReport += "     • $rec`n"
            }
        }
        $txtReport += "`n"
    }
    
    # Add summary
    $txtReport += @"
RECOMMENDED ACTIONS:
===================
1. Address all CRITICAL issues first (marked with '✗' in red)
2. Review and fix WARNING issues (marked with '⚠' in yellow)
3. Implement the recommendations provided
4. Re-run this audit after making changes

NEXT STEPS:
===========
- For enterprise environments: Consider Microsoft Defender for Endpoint
- Implement regular security audits (weekly/monthly)
- Keep Windows and all software updated
- Follow principle of least privilege for user accounts

Report generated by Windows Security Audit & Hardening Tool
===========================================
"@
    
    # Save TXT report
    $txtFileName = "$OutputPath\security-audit-$timestamp-$computerName.txt"
    $txtReport | Out-File -FilePath $txtFileName -Encoding UTF8
    Write-Host "  ✓ Text report saved: $txtFileName" -ForegroundColor Green
    
    # 2. Generate simple HTML report
    $htmlReport = @"
<!DOCTYPE html>
<html>
<head>
    <title>Windows Security Audit Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { background: #2c3e50; color: white; padding: 20px; border-radius: 5px; }
        .score { font-size: 24px; padding: 15px; margin: 20px 0; border-radius: 5px; text-align: center; }
        .good { background: #27ae60; color: white; }
        .fair { background: #f39c12; color: white; }
        .poor { background: #e74c3c; color: white; }
        .section { background: #f8f9fa; padding: 15px; margin: 10px 0; border-left: 4px solid #3498db; }
        .issue { color: #c0392b; }
        .recommendation { color: #27ae60; }
        .footer { margin-top: 30px; font-size: 12px; color: #7f8c8d; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Windows Security Audit Report</h1>
        <p>Generated on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss") for $computerName</p>
    </div>
    
    <div class="score $(if ($AuditResults.OverallScore -ge 80) { 'good' } elseif ($AuditResults.OverallScore -ge 60) { 'fair' } else { 'poor' })">
        <h2>Overall Security Score: $($AuditResults.OverallScore)/100</h2>
        <p>$(if ($AuditResults.OverallScore -ge 80) {
            "STATUS: GOOD - System is reasonably secure"
        } elseif ($AuditResults.OverallScore -ge 60) {
            "STATUS: FAIR - Some improvements needed"
        } else {
            "STATUS: POOR - Immediate action required"
        })</p>
    </div>
    
    <h2>Detailed Findings</h2>
"@
    
    # Add sections dynamically
    if ($AuditResults.SystemInfo) {
        $htmlReport += @"
    <div class="section">
        <h3>System Information</h3>
        <p><strong>Score:</strong> $($AuditResults.SystemInfo.SecurityScore)/100</p>
        <p><strong>OS:</strong> $($AuditResults.SystemInfo.OSName)</p>
        <p><strong>Version:</strong> $($AuditResults.SystemInfo.OSVersion)</p>
"@
        if ($AuditResults.SystemInfo.Issues.Count -gt 0) {
            $htmlReport += "<p class='issue'><strong>Issues:</strong></p><ul>"
            foreach ($issue in $AuditResults.SystemInfo.Issues) {
                $htmlReport += "<li>$issue</li>"
            }
            $htmlReport += "</ul>"
        }
        $htmlReport += "</div>"
    }
    
    if ($AuditResults.AccountInfo) {
        $htmlReport += @"
    <div class="section">
        <h3>Account Security</h3>
        <p><strong>Score:</strong> $($AuditResults.AccountInfo.Score)/100</p>
"@
        if ($AuditResults.AccountInfo.Issues.Count -gt 0) {
            $htmlReport += "<p class='issue'><strong>Issues:</strong></p><ul>"
            foreach ($issue in $AuditResults.AccountInfo.Issues) {
                $htmlReport += "<li>$issue</li>"
            }
            $htmlReport += "</ul>"
        }
        if ($AuditResults.AccountInfo.Recommendations.Count -gt 0) {
            $htmlReport += "<p class='recommendation'><strong>Recommendations:</strong></p><ul>"
            foreach ($rec in $AuditResults.AccountInfo.Recommendations) {
                $htmlReport += "<li>$rec</li>"
            }
            $htmlReport += "</ul>"
        }
        $htmlReport += "</div>"
    }
    
    # Close HTML
    $htmlReport += @"
    <div class="footer">
        <p>Report generated by Windows Security Audit & Hardening Tool v1.0</p>
        <p>This is an automated security assessment tool. For comprehensive security analysis, 
        consult with cybersecurity professionals.</p>
    </div>
</body>
</html>
"@
    
    # Save HTML report
    $htmlFileName = "$OutputPath\security-audit-$timestamp-$computerName.html"
    $htmlReport | Out-File -FilePath $htmlFileName -Encoding UTF8
    Write-Host "  ✓ HTML report saved: $htmlFileName" -ForegroundColor Green
    
    return @{
        TextReport = $txtFileName
        HtmlReport = $htmlFileName
    }
}